name: Update README ⭐
on:
  schedule:
    # run at...
    # 49 minutes past the hour
    # every 4th hour
    # on days 1-25
    # only in December
    # every day of the week.
    - cron: "49 */4 1-25 12 *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
